#!/usr/bin/env python3
# Slough trace animation  -  generated by slough dry-run library

import turtle
import time
from typing import Any

# -- Trace data --------------------------------------------------------------

SOURCE_LINES: list[str] = []
STEPS:list[dict] = []

DELAY = 0.8
FONT = ("Consolas", 10, "normal")
FONT_BOLD = ("Consolas", 11, "bold")
FONT_SMALL = ("Consolas", 8, "normal")
BG = "#ffffff"
CODE_BG = "#f5f5f5"
VAR_BG = "#fafafa"
HIGHLIGHT = "#1a1a1a"
TEXT_COLOR = "#000000"
LINE_NUM_COLOR = "#888888"
KEY_COLOR = "#1a56db"
VAL_COLOR = "#16a34a"
BOX_COLOR = "#d4d4d4"
ACCENT = "#7c3aed"

screen = turtle.Screen()
screen.setup(1400, 900)
screen.bgcolor(BG)
screen.tracer(0)
screen.title("Slough Dry-Run Animation")
screen.cv._rootwindow.resizable(False, False)

t = turtle.Turtle()
t.speed(0)
t.hideturtle()


# -- Drawing helpers ---------------------------------------------------------

def draw_rect(x: float, y: float, w: float, h: float, color: str) -> None:
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor(color)
    t.pencolor(color)
    t.begin_fill()
    for _ in range(2):
        t.forward(w)
        t.right(90)
        t.forward(h)
        t.right(90)
    t.end_fill()


def write_text(x: float, y: float, text: str,
               font: tuple = FONT, color: str = TEXT_COLOR,
               align: str = "left") -> None:
    t.penup()
    t.goto(x, y)
    t.pencolor(color)
    t.write(text, font=font, align=align)


def draw_arrow(x1: float, y1: float, x2: float, y2: float) -> None:
    t.penup()
    t.goto(x1, y1)
    t.pendown()
    t.pencolor(ACCENT)
    t.pensize(2)
    t.goto(x2, y2)
    t.pensize(1)


# -- Source code panel -------------------------------------------------------

def draw_code_panel(source_lines: list[str], highlight_lineno: int | None = None) -> None:
    draw_rect(-680, 380, 660, 770, CODE_BG)

    write_text(-670, 355, " Source", FONT_BOLD, ACCENT)
    write_text(-670, 340, " Code", FONT_BOLD, ACCENT)

    line_h = 20
    visible = 35
    start_line = max(0, (highlight_lineno or 1) - visible // 2)
    end_line = min(len(source_lines), start_line + visible)

    for i in range(start_line, end_line):
        lineno = i + 1
        y = 310 - (i - start_line) * line_h
        raw = source_lines[i].rstrip("\\n").rstrip("\\r")

        if highlight_lineno == lineno:
            draw_rect(-678, y - 4, 656, line_h, "#e8f0fe")
            write_text(-670, y - line_h + 16, f"{lineno:>3}", FONT_SMALL, LINE_NUM_COLOR)
            write_text(-640, y - line_h + 16, raw, FONT, TEXT_COLOR)
            write_text(-640, y - line_h + 16, raw, ("Consolas", 10, "bold"), HIGHLIGHT)
        else:
            write_text(-670, y - line_h + 16, f"{lineno:>3}", FONT_SMALL, LINE_NUM_COLOR)
            write_text(-640, y - line_h + 16, raw, FONT, TEXT_COLOR)


# -- Variables panel ---------------------------------------------------------

def draw_vars_panel(vars_dict: dict[str, Any], step_idx: int,
                    total_steps: int, event: str, func_name: str,
                    return_value: Any | None) -> None:
    draw_rect(10, 380, 660, 770, VAR_BG)

    write_text(20, 355, " Variables", FONT_BOLD, ACCENT)

    info = f"Step {step_idx}/{total_steps}  |  {event}  |  {func_name}"
    write_text(20, 330, info, ("Consolas", 9, "normal"), LINE_NUM_COLOR)

    if return_value is not None and event in ("return", "exception"):
        write_text(20, 305, f"return: {return_value!r}", FONT_BOLD, VAL_COLOR)

    y = 280
    line_h = 18
    for key, val in vars_dict.items():
        if key == "self":
            continue
        if y < -360:
            write_text(20, y, "... (truncated)", FONT, LINE_NUM_COLOR)
            break

        write_text(20, y - line_h + 14, f"{key} =", FONT, KEY_COLOR)
        val_str = repr(val)
        if len(val_str) > 80:
            val_str = val_str[:77] + "..."
        write_text(140, y - line_h + 14, val_str, FONT, VAL_COLOR)

        y -= line_h


# -- Data structure visualization -------------------------------------------

def _is_simple_list(lst: list) -> bool:
    return (
        len(lst) <= 20
        and all(not isinstance(v, (list, dict)) for v in lst)
    )


def draw_list_ds(lst: list, y_start: float) -> tuple[bool, float]:
    if not _is_simple_list(lst):
        return False, y_start

    box_w = 48
    box_h = 28
    gap = 4
    total_w = len(lst) * (box_w + gap)
    start_x = 40

    if total_w > 620:
        box_w = max(20, 620 // len(lst) - gap)
        total_w = len(lst) * (box_w + gap)

    draw_rect(start_x - 4, y_start + 4, total_w + 8, box_h + 24, "#f0f0f0")

    for i, val in enumerate(lst):
        bx = start_x + i * (box_w + gap)
        draw_rect(bx, y_start, box_w, box_h, BOX_COLOR)
        label = str(val) if len(str(val)) < 6 else str(val)[:5]
        write_text(bx + box_w / 2, y_start + box_h / 2 - 5, label,
                   FONT_SMALL, TEXT_COLOR, "center")
        write_text(bx + box_w / 2, y_start - 14, str(i),
                   ("Consolas", 7, "normal"), LINE_NUM_COLOR, "center")

    return True, y_start - box_h - 30


def draw_dict_ds(d: dict, y_start: float) -> tuple[bool, float]:
    if not d:
        return False, y_start
    line_h = 16
    count = 0
    for k, v in d.items():
        if y_start - count * line_h < -360:
            break
        label = f"{k!r}  ->  {v!r}"
        if len(label) > 70:
            label = label[:67] + "..."
        write_text(40, y_start - count * line_h, label,
                   ("Consolas", 9, "normal"), KEY_COLOR)
        count += 1
    return count > 0, y_start - count * line_h - 10


def draw_tree_ds(node: Any, y_start: float) -> tuple[bool, float]:
    if not hasattr(node, "val"):
        return False, y_start

    visited: set[int] = set()

    def _node_height(n: Any) -> int:
        if n is None or id(n) in visited:
            return 0
        visited.add(id(n))
        h = 1
        if hasattr(n, "next") and n.next is not None:
            h = max(h, 1 + _node_height(n.next))
        if hasattr(n, "left") and n.left is not None:
            h = max(h, 1 + _node_height(n.left))
        if hasattr(n, "right") and n.right is not None:
            h = max(h, 1 + _node_height(n.right))
        return h

    def _is_linked_list(n: Any) -> bool:
        if not hasattr(n, "next"):
            return False
        return not (hasattr(n, "left") or hasattr(n, "right"))

    h = _node_height(node)
    if h > 8:
        write_text(40, y_start, f"Tree ({h} levels) - too large to render",
                   FONT, LINE_NUM_COLOR)
        return True, y_start - 20

    if _is_linked_list(node):
        visited.clear()
        x = 40
        y = y_start
        n = node
        node_w = 44
        node_h = 28
        gap = 10
        while n is not None and id(n) not in visited:
            visited.add(id(n))
            draw_rect(x, y, node_w, node_h, BOX_COLOR)
            label = str(n.val) if len(str(n.val)) < 5 else str(n.val)[:4]
            write_text(x + node_w / 2, y + node_h / 2 - 5, label,
                       FONT_SMALL, TEXT_COLOR, "center")
            if hasattr(n, "next") and n.next is not None:
                arrow_x = x + node_w + 2
                draw_arrow(arrow_x, y + node_h / 2, arrow_x + 6, y + node_h / 2)
            x += node_w + gap
            if x > 640:
                write_text(x, y, "...", FONT, LINE_NUM_COLOR)
                break
            n = getattr(n, "next", None)

        return True, y - 20 - node_h

    return False, y_start


def draw_data_structure(name: str, value: Any,
                        y_start: float) -> tuple[bool, float]:
    if isinstance(value, dict):
        return draw_dict_ds(value, y_start)
    if isinstance(value, list):
        if len(value) <= 1:
            return False, y_start
        if _is_simple_list(value):
            return draw_list_ds(value, y_start)
    if isinstance(value, tuple):
        if len(value) <= 1:
            return False, y_start
        return draw_list_ds(list(value), y_start)
    if not isinstance(value, (int, float, bool, str, bytes, type(None))):
        if hasattr(value, "val"):
            return draw_tree_ds(value, y_start)
    return False, y_start


# -- Summary screen ----------------------------------------------------------

def draw_summary(steps: list[dict]) -> None:
    draw_rect(-680, 400, 1360, 810, BG)
    total = len(steps)
    passed = 0
    y = 300
    for tc_data in steps:
        rv = tc_data.get("return_value")
        exp = tc_data.get("expected")
        status = "PASS" if rv == exp else "FAIL" if exp is not None else "?"
        if status == "PASS":
            passed += 1
        color = VAL_COLOR if status == "PASS" else ("#dc2626" if status == "FAIL" else LINE_NUM_COLOR)
        write_text(-400, y, f"  Test Case {STEPS.index(tc_data) + 1}:  "
                   f"return {rv!r}  expected {exp!r}  {status}",
                   FONT, color)
        y -= 24

    write_text(0, 350, f"  {passed}/{total} tests passed",
               ("Consolas", 16, "bold"),
               VAL_COLOR if passed == total else "#dc2626", "center")
    write_text(0, -100, "Click to exit",
               FONT, LINE_NUM_COLOR, "center")


# -- Animation loop ----------------------------------------------------------

def render_header() -> None:
    draw_rect(-680, 400, 1360, 40, BG)
    write_text(-670, 412, " slough  --  Dry-Run Animation",
               FONT_BOLD, ACCENT)


def animate(source_lines: list[str] | None = None,
            steps: list[dict] | None = None) -> None:
    if source_lines is None:
        source_lines = SOURCE_LINES
    if steps is None:
        steps = STEPS

    render_header()

    all_steps = []
    for tc_idx, tc_data in enumerate(steps):
        for step in tc_data["steps"]:
            all_steps.append((tc_idx, step))
        final = tc_data["steps"][-1] if tc_data["steps"] else {}
        all_steps.append((tc_idx, {
            "lineno": final.get("lineno", 0),
            "event": "test_complete",
            "func_name": "",
            "vars": {},
            "return_value": tc_data["return_value"],
        }))

    total = len(all_steps)

    for i, (tc_idx, step) in enumerate(all_steps):
        if step["event"] == "test_complete":
            draw_code_panel(source_lines, None)
        else:
            draw_code_panel(source_lines, step.get("lineno"))

        draw_vars_panel(
            step.get("vars", {}),
            i + 1, total,
            step.get("event", ""),
            step.get("func_name", ""),
            step.get("return_value"),
        )

        write_text(-670, -390,
                   f"Test case {tc_idx + 1} of {len(steps)}",
                   FONT_SMALL, LINE_NUM_COLOR)

        if step["event"] == "test_complete":
            rv = step.get("return_value")
            expected = steps[tc_idx].get("expected")
            line = f"Return: {rv!r}"
            if expected is not None:
                if rv == expected:
                    line += "  PASS"
                else:
                    line += f"  FAIL  (expected: {expected!r})"
            color = VAL_COLOR if rv == expected else "#dc2626"
            write_text(20, -390, line, FONT_BOLD, color)

        screen.update()
        time.sleep(DELAY)

    draw_summary(steps)
    screen.update()
    screen.exitonclick()


if __name__ == "__main__":
    animate(source_lines=SOURCE_LINES, steps=STEPS)
